# This file was generated by GoReleaser. DO NOT EDIT.
cask "mocktail" do
  version "4.0.3"

  on_macos do
    on_intel do
      sha256 "c67abb7b2ea074a5102839310624588199394dec0955610859354869122f3a0b"
      url "https://github.com/Huseyinnurbaki/mocktail/releases/download/v#{version}/mocktail_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "008545d3d24d31c4292533425f985c0636e7fa329a14c85282008653f040f356"
      url "https://github.com/Huseyinnurbaki/mocktail/releases/download/v#{version}/mocktail_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "e3c9754ba16e343882184288cc4a7ad59f8cee669146004bfb073cbe62266d2a"
      url "https://github.com/Huseyinnurbaki/mocktail/releases/download/v#{version}/mocktail_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "db4c4a65e00c87a27b4e9b4caaad3b07819a460a09ca26382d3fdd46a7e0a582"
      url "https://github.com/Huseyinnurbaki/mocktail/releases/download/v#{version}/mocktail_#{version}_linux_arm64.tar.gz"
    end
  end

  name "mocktail"
  desc "Self-hosted mock API server with a dashboard, in a single binary"
  homepage "https://getmocktail.com"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "mocktail"

  postflight do
    system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/mocktail"]
  end

  # No zap stanza required

  caveats <<~EOS
    Start Mocktail with:  mocktail
    Then open the dashboard at http://localhost:6625
  EOS
end
