# This file was generated by GoReleaser. DO NOT EDIT.
cask "mocktail" do
  version "4.0.0-rc.2"

  on_macos do
    on_intel do
      sha256 "5537654f0c3a5e36ac336d9d125a7f52690dc688e1bcbfbba9baad0542ea3d87"
      url "https://github.com/Huseyinnurbaki/mocktail/releases/download/v#{version}/mocktail_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "c3a407f52739ca10258b6f47c44ba20dd8f7b64bdf7559b64bb3be507e70924e"
      url "https://github.com/Huseyinnurbaki/mocktail/releases/download/v#{version}/mocktail_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "61cae2dd0c282d82a073fbded8d9bd4c85936c1cac46c79cb142f3b6c4c4efbf"
      url "https://github.com/Huseyinnurbaki/mocktail/releases/download/v#{version}/mocktail_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "10bd15104732e39c7b03732e19e541f50a40c4c146d6772560516c7814724f74"
      url "https://github.com/Huseyinnurbaki/mocktail/releases/download/v#{version}/mocktail_#{version}_linux_arm64.tar.gz"
    end
  end

  name "mocktail"
  desc "Self-hosted mock API server with a dashboard, in a single binary"
  homepage "https://getmocktail.com"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "mocktail"

  postflight do
    system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/mocktail"]
  end

  # No zap stanza required

  caveats <<~EOS
    Start Mocktail with:  mocktail
    Then open the dashboard at http://localhost:6625
  EOS
end
