# This file was generated by GoReleaser. DO NOT EDIT.
cask "mocktail" do
  version "4.0.2"

  on_macos do
    on_intel do
      sha256 "5d841d16e8af346eb66da177134700dd93756e7a482823baa417d59774be3c29"
      url "https://github.com/Huseyinnurbaki/mocktail/releases/download/v#{version}/mocktail_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "6c9f771ad9c53a43f2adb2bdb0b19b7667939cb5b7f28a2077d40d9fff214eb6"
      url "https://github.com/Huseyinnurbaki/mocktail/releases/download/v#{version}/mocktail_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "16d2efdfdb9f85ed2f8f267b58eb9a6221534b86fb4bc80c1bb0c0c0feec31aa"
      url "https://github.com/Huseyinnurbaki/mocktail/releases/download/v#{version}/mocktail_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "c1195d96a6a69a7d8432e3aa0a5e75a4ec75f8aba32770608c0d291c132becca"
      url "https://github.com/Huseyinnurbaki/mocktail/releases/download/v#{version}/mocktail_#{version}_linux_arm64.tar.gz"
    end
  end

  name "mocktail"
  desc "Self-hosted mock API server with a dashboard, in a single binary"
  homepage "https://getmocktail.com"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "mocktail"

  postflight do
    system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/mocktail"]
  end

  # No zap stanza required

  caveats <<~EOS
    Start Mocktail with:  mocktail
    Then open the dashboard at http://localhost:6625
  EOS
end
